### ISSUE TITLE
Drop outdated updates

### ISSUE THREAD

**Issue by BjoernPetersen** [woog-life/api#4]

**Comment by torbencarstens** [comment]
But how will we get a history view in the frontend? :o

**Comment by BjoernPetersen** [comment]
This is just about dropping new updates if our current value is more recent. It's kind of a non-issue, but you know how it is.

**Comment by BjoernPetersen** [comment]
Since #3 has been implemented, received values are simply inserted with their respective timestamp into the database and discarded if they're duplicates. Consequently, this has become a non-issue.
