### ISSUE TITLE
`formatRegion` should be case-insensitive

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/api#50]
`formatRegion=DE` -> works fine
`formatRegion=de` -> `{"errorMessage":"Invalid region identifier"}`

**Comment by BjoernPetersen** [comment]
The ISO 3166-1 alpha-2 country codes are usually specified in upper case. Allowing lower case values here would just lead to confusion with language codes (ISO 639-1).

**Comment by torbencarstens** [comment]
Sure, we might as well follow the country standard instead of choosing based on languages arbitrarily.

We should at least cover the basic country codes from our users though -> `BE`, `CH` since we have lakes in both countries and it isn't unlikely to retrieve such a CC.

The allowed formatting would need to be extended every time a lake in a new country is added, I don't think that we have a DoD already where we could include this?

**Comment by torbencarstens** [comment]
It would also be useful if we'd have either:

1. a list of valid options available via the API + the default
2. an endpoint which returns the correct value for an input (i.e. chooses the default if the value is not available)

otherwise this logic has to be implemented by each client and each client would need to be updated when the list of allowed CCs changes.

**Comment by BjoernPetersen** [comment]
Hm, I tried to be lazy about this, but you're right, the correct thing to do for a client is looking up the actual user locale and sending the country part to the API. Thus, the API should support all ISO country codes. 

Unfortunately, `Locale` related stuff seems to be buried in the UI parts of Dart, and I'm not sure I can use those without Flutter, which is the reason for the current (magnificent) implementation of `Region`: https://github.com/woog-life/api/blob/main/lib/src/domain/model/region.dart

Worst case: I'll convert a CSV of ISO country codes to a Dart enum using a Python script.

**Comment by BjoernPetersen** [comment]
If the API supported all valid ISO country codes, we wouldn't need a separate endpoint to retrieve the supported ones, right?

**Comment by torbencarstens** [comment]
Yes, that would remove the necessity of a separate endpoint.
Clients would just not include the `formatRegion` parameter if none is available.

This might happen, the frontend uses the `Accept-Language` header which might include a region but does not have to.
In practice, browsers should sent this.

Although the subtag (second part of `{lang}-{extra info}`) might also be of a different type than CC (e.g. LATIN), this needs to be handled by the client though since it's browser specific.

BUT then having a list of supported CCs might still be good if there is a two-letter code in the subtag which isn't a valid CC.

**Comment by BjoernPetersen** [comment]
All ISO recognized country codes are now accepted.
