### ISSUE TITLE
`formatRegion` should be available on `/lake/{uuid}`

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/api#51]
```bash
$ curl -s https://api.woog.life/lake/ab6fbeb2-be73-4223-8f04-425929339838\?precision\=1\&formatRegion\=DE | jq '.data.preciseTemperature'
"10.4"
```

```bash
$ curl -s https://api.woog.life/lake/ab6fbeb2-be73-4223-8f04-425929339838/temperature\?precision\=1\&formatRegion\=DE | jq '.preciseTemperature'
"10,4"
```

**Comment by BjoernPetersen** [comment]
I noticed that the `/lake/{id}` endpoint returns temperature data yesterday. That shouldn't even happen according to the docs 😅. Consider the `data` part of that operation's response deprecated.

**Comment by torbencarstens** [comment]
God damn it, I feared this would happen :D

**Comment by torbencarstens** [comment]
Please wait with merging this change into master until https://github.com/woog-life/preliminary-frontend/issues/73 is fixed.

**Comment by BjoernPetersen** [comment]
I didn't plan on removing the `data` property yet, because I was almost certain some other microservice (nanoservice?) depends on it. I just won't introduce updates (like `formatRegion`) for it.

**Comment by torbencarstens** [comment]
I'll check the other microservices but I know that some are using the /temperature endpoint (e.g. telegram-updater/preliminary-frontend)

**Comment by torbencarstens** [comment]
I think that was everything, the tooter isn't updated but it isn't working anyways so it's not an issue.

The data property on `lake/{id}` shouldn't be used anywhere anymore as of now (at least not from any of our clients).

I think we can close this issue and open a new one to deprecate the `data` property on this endpoint.
