### ISSUE TITLE
`data` property on `/lake/{id}` endpoint should be deprecated

### ISSUE THREAD

**Issue by torbencarstens** [woog-life/api#77]
see #51 for infos

**Comment by BjoernPetersen** [comment]
Do you think it can be safely removed at this point? It's been "deprecated" for a while now, there just isn't a good HTTP/REST  mechanism to communicate that.

**Comment by torbencarstens** [comment]
I think we can safely remove this for now.

For dealing with deprecationa/removals in the future we might want to think about versioning the api.
